#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'session'
    style = 'plain'
    foreground = 'green'
    background = 'transparent'
    template = '{{ .HostName }} '

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    foreground = 'blue'
    background = 'transparent'
    template = '{{ .Path }} '

    [blocks.segments.properties]
      style = 'full'

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    foreground = 'yellow'
    background = 'transparent'
    background_templates = [
      '{{ if or (.Working.Changed) (.Staging.Changed) }}#FFEB3B{{ end }}',
      '{{ if and (gt .Ahead 0) (gt .Behind 0) }}#FFCC80{{ end }}',
      '{{ if gt .Ahead 0 }}#B388FF{{ end }}',
      '{{ if gt .Behind 0 }}#B388FB{{ end }}'
    ]
    template = '{{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }} {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }} {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }} {{ .StashCount }}{{ end }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'status'
    style = 'plain'
    foreground = '#D4E157'
    foreground_templates = ['{{ if gt .Code 0 }}#FF5252{{ end }}']
    template = '❯ '

    [blocks.segments.properties]
      always_enabled = true

[transient_prompt]
  foreground = '#D4E157'
  background = 'transparent'
  template = '❯ '
